### ISSUE TITLE
Weird stuff in the Nether

### ISSUE THREAD

**Issue by JumperREDACTED** [dvitski/undergroundambientlighting#4]
I assume this mod shouldn't work in the Nether at all, but if it is, there is the issue that it causes really sharp differences between dark and light places
![2021-10-21_10 32 35](https://user-images.githubusercontent.com/83337894/138245386-e34d8db2-1c2a-49f6-89aa-051c0650e2bf.png)

**Comment by dvitski** [comment]
Fixed in v2.1.1 :)

[Forge](https://github.com/andantet/undergroundambientlighting/releases/tag/2.1.1%2B1.17-forge) | [Fabric](https://github.com/andantet/undergroundambientlighting/releases/tag/2.1.1%2B1.17-fabric)
